name: React CI

on:
  push:
    branches:
      - main

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "18"
      - run: npm install
      - run: npm run build --if-present
      # - run: npm run test


deploy:
  name: Firebase deploy
  needs: [build]
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up Node.js
      uses: actions/setup-node@v3.5.1
      with:
        node-version: "14"  # Choose a supported Node.js version
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Install Dependencies and Deploy
      run: |
        npm install
        npm run build
        firebase deploy

